.TH "concept_forces" 3 "Sun Apr 6 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
concept_forces \- Forces in oFreq 
\fBTodo\fP
.RS 4
write documentation for oFreq forces\&.
.IP "\(bu" 2
specifically mention that you can define forces and not use them\&. THis allows you to build up a library of forces\&.
.PP
.RE
.PP
.PP
.SH "What is a Force?"
.PP
.PP
.SH "Required Information"
.PP
.PP
.SH "Usage"
.PP

