.TH "concept_overall" 3 "Sun Apr 6 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
concept_overall \- Overall Process 
\fBTodo\fP
.RS 4
write documentation for ofreq overall process\&.
.RE
.PP
.PP
.SH "Create New Directory"
.PP
.PP
.SH "Define Inputs"
.PP
.PP
.SS "System Control"
.PP
control\&.in file\&.
.PP
.SS "Bodies"
.PP
bodies\&.in file\&.
.PP
.SS "Hydrodynamic Data"
.PP
data\&.in file\&.
.PP
.SS "User Forces"
.PP
forces\&.in file
.PP
.SS "Sea Environment"
.PP
seaenv\&.in file
.PP
.SH "Run Program"
.PP
.PP
.SH "Review Outputs"
.PP

