.TH "custom_motion_models" 3 "Sun Apr 6 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
custom_motion_models \- Custom Motion Models 
\fBTodo\fP
.RS 4
write documentation for custom motion models\&. This will be a really important one\&. So give it some effort\&. Start with the documentation already present in the source code\&.
.RE
.PP
.PP
.SH "Defining Your Own Motion Models"
.PP
.PP
.SH "Available Functions"
.PP
.PP
.SH "Custom parameters"
.PP

