.TH "efficiency_absolute" 3 "Sun Apr 6 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
efficiency_absolute \- Absolute Efficiency 
\fBTodo\fP
.RS 4
write documentation for Absolute Effciiency\&. Refer back to the Porpoise Buoy documentation\&. That should have some useful stuff on the various types of efficiency calculated\&.
.RE
.PP
.PP
.SH "Output"
.PP
.PP
.SH "Calculation Method"
.PP
.PP
.SH "Limitations"
.PP
.PP
.SH "Application to Custom Motion Models"
.PP
.PP
.SH "RAO Calculation"
.PP
.PP
State how the RAO is calculated\&. For every output, ofreq calculates both the true response value, and the RAO for that value\&. They are listed sequentially\&. First the response, then the RAO\&.
.PP
.SS "RAO Normalization\&."
.PP
Sometimes it can be very confusing which part of the input wave properties are used to normalize the output\&. This section should explicitely state how the RAO was calculated\&.
.PP
.SS "RAO Units"
.PP
Sometimes it can be very confusing what the units of an RAO are\&. So this should clarify\&. 
