.TH "file_structure" 3 "Sun Apr 6 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
file_structure \- File Structure 
\fBTodo\fP
.RS 4
Write file structure documentation\&.
.RE
.PP
.PP
.SH "System Folder"
.PP
.PP
Stuff
.PP
.SH "Constant Folder"
.PP
.PP
Stuff
.PP
.SH "Output Folders"
.PP
.PP
.SS "Wave direction folders"
.PP
.SS "Resonant Frequency folders"

