.TH "forces" 3 "Sun Apr 6 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
forces \- Forces\&.in Input File 
\fBTodo\fP
.RS 4
write forces\&.in input file
.IP "\(bu" 2
Main purpose for file
.IP "\(bu" 2
Typical inputs
.IP "\(bu" 2
Required inputs
.IP "\(bu" 2
Default values\&.
.PP
.RE
.PP

