.TH "input_files" 3 "Sun Apr 6 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
input_files \- Input Files 
\fBTodo\fP
.RS 4
Write intro documentation for input files\&.
.RE
.PP
.PP
.SH "System Control Files"
.PP
.PP
\fBControl\&.in Input File\fP
.PP
.SH "Run Definition Files"
.PP
.PP
\fBBodies\&.in Input File\fP
.PP
\fBData\&.in Input File\fP
.PP
\fBForces\&.in Input File\fP
.PP
\fBSeaenv\&.in Input File\fP
.PP
\fBOutputs\&.in Input File\fP 
