.TH "installation_instructions" 3 "Sun Apr 6 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
installation_instructions \- Installation Instructions 
\fBTodo\fP
.RS 4
Write installation instructions\&.
.IP "\(bu" 2
First work out how to install the software\&.
.IP "\(bu" 2
Then write the instructions\&.
.PP
.RE
.PP
.PP
\fBStill in Development\fP 
