.TH "motion_model" 3 "Sun Apr 6 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
motion_model \- Motion Model 
\fBTodo\fP
.RS 4
Write general purpose information for motion models\&.
.IP "\(bu" 2
What are they\&.
.IP "\(bu" 2
Why do we need them\&.
.IP "\(bu" 2
Do we care about them?
.IP "\(bu" 2
What can we do with them\&. Emphasise that they let us convert motions into forces\&.
.PP
.RE
.PP
.PP
.SH "Standard Motion Models"
.PP
.PP
\fBStandard Motion Models\fP
.PP
.SH "Custom Motion Models"
.PP
.PP
\fBCustom Motion Models\fP 
