.TH "standard_motion_models" 3 "Sun Apr 6 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
standard_motion_models \- Standard Motion Models 
\fBTodo\fP
.RS 4
Write page for standard motion models\&.
.RE
.PP
.PP
.SH "Standard Motion Models"
.PP
.PP
\fB6 Degree of Freedom (6 DOF) Motion Model\fP 
