.TH "todo" 3 "Sun Apr 6 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.IP "\fBPage \fB6 Degree of Freedom (6 DOF) Motion Model\fP \fP" 1c
Write 6 DOF motion model documentation\&. Include all the documentation necessary\&. 
.IP "\fBPage \fBAbsolute Efficiency\fP \fP" 1c
write documentation for Absolute Effciiency\&. Refer back to the Porpoise Buoy documentation\&. That should have some useful stuff on the various types of efficiency calculated\&. 
.IP "\fBPage \fBBodies in oFreq\fP \fP" 1c
write documentation for ofreq bodies\&. 
.IP "\fBPage \fBBodies\&.in Input File\fP \fP" 1c
write bodies\&.in input file
.IP "\(bu" 2
Main purpose for file
.IP "\(bu" 2
Typical inputs
.IP "\(bu" 2
Required inputs
.IP "\(bu" 2
Default values\&. 
.PP
.IP "\fBPage \fBConcepts\fP \fP" 1c
Write simple introduction to concepts\&. 
.IP "\fBPage \fBControl\&.in Input File\fP \fP" 1c
write control\&.in input file
.IP "\(bu" 2
Main purpose for file
.IP "\(bu" 2
Typical inputs
.IP "\(bu" 2
Required inputs
.IP "\(bu" 2
Default values\&. 
.PP
.IP "\fBPage \fBCustom Motion Models\fP \fP" 1c
write documentation for custom motion models\&. This will be a really important one\&. So give it some effort\&. Start with the documentation already present in the source code\&. 
.IP "\fBPage \fBData\&.in Input File\fP \fP" 1c
write data\&.in input file
.IP "\(bu" 2
Main purpose for file
.IP "\(bu" 2
Typical inputs
.IP "\(bu" 2
Required inputs
.IP "\(bu" 2
Default values\&. 
.PP
.IP "\fBPage \fBDefinitions\fP \fP" 1c
Write definitions of common terms used in ofreq\&. See if I can find some way to generate a list that will automatically link the terms\&. I may need to trick Doxygen to believe that definition is a function or some other similar piece of code\&. 
.IP "\fBPage \fBFile Structure\fP \fP" 1c
Write file structure documentation\&. 
.IP "\fBPage \fBForces in oFreq\fP \fP" 1c
write documentation for oFreq forces\&.
.IP "\(bu" 2
specifically mention that you can define forces and not use them\&. THis allows you to build up a library of forces\&. 
.PP
.IP "\fBPage \fBForces\&.in Input File\fP \fP" 1c
write forces\&.in input file
.IP "\(bu" 2
Main purpose for file
.IP "\(bu" 2
Typical inputs
.IP "\(bu" 2
Required inputs
.IP "\(bu" 2
Default values\&. 
.PP
.IP "\fBPage \fBGlobal Acceleration\fP \fP" 1c
write documentation for global acceleration\&. 
.IP "\fBPage \fBGlobal Derivative\fP \fP" 1c
write documentation for global derivative\&. 
.IP "\fBPage \fBGlobal Forces\fP \fP" 1c
write documentation for global forces 
.IP "\fBPage \fBGlobal Motion\fP \fP" 1c
write documentation for global motions\&. 
.IP "\fBPage \fBGlobal Velocity\fP \fP" 1c
write documentation for global velocity\&. 
.IP "\fBPage \fBInput Files\fP \fP" 1c
Write intro documentation for input files\&. 
.IP "\fBPage \fBInstallation Instructions\fP \fP" 1c
Write installation instructions\&.
.IP "\(bu" 2
First work out how to install the software\&.
.IP "\(bu" 2
Then write the instructions\&. 
.PP
.IP "\fBPage \fBLocal Acceleration\fP \fP" 1c
write documentation for local acceleration\&. 
.IP "\fBPage \fBLocal Derivative\fP \fP" 1c
write documentation for local derivative\&. 
.IP "\fBPage \fBLocal Forces\fP \fP" 1c
write documentation for local forces 
.IP "\fBPage \fBLocal Motion\fP \fP" 1c
write documentation for local motion\&. 
.IP "\fBPage \fBLocal Velocity\fP \fP" 1c
write documentation for local velocity\&. 
.IP "\fBPage \fBMotion Model\fP \fP" 1c
Write general purpose information for motion models\&.
.IP "\(bu" 2
What are they\&.
.IP "\(bu" 2
Why do we need them\&.
.IP "\(bu" 2
Do we care about them?
.IP "\(bu" 2
What can we do with them\&. Emphasise that they let us convert motions into forces\&. 
.PP
.IP "\fBPage \fBMotion Sickness Index\fP \fP" 1c
write documentation for Motion Sickness Index\&. There will probably also be some inputs to enter\&. 
.IP "\fBPage \fBOutputs\fP \fP" 1c
write documentation for outputs page\&. 
.IP "\fBPage \fBOutputs\&.in Input File\fP \fP" 1c
write outputs\&.in input file
.IP "\(bu" 2
Main purpose for file
.IP "\(bu" 2
Typical inputs
.IP "\(bu" 2
Required inputs
.IP "\(bu" 2
Default values\&. 
.PP
.IP "\fBPage \fBOverall Process\fP \fP" 1c
write documentation for ofreq overall process\&. 
.IP "\fBPage \fBPower\fP \fP" 1c
write documentation for Power\&. Power extracted should be based on each equation entered\&. We need a summary for each force\&. Possibly also a summary for total force\&. Remember that only a force, reactive in nature, can extract power\&. 
.IP "\fBPage \fBQuick Start\fP \fP" 1c
write Quick Start documentation\&. (Low priority)\&. 
.IP "\fBPage \fBRelative Efficiency\fP \fP" 1c
write documentation for Relative Effciiency\&. Refer back to the Porpoise Buoy documentation\&. That should have some useful stuff on the various types of efficiency calculated\&. 
.IP "\fBPage \fBSea Environment\fP \fP" 1c
write documentation for oFreq sea environment\&. 
.IP "\fBPage \fBSeaenv\&.in Input File\fP \fP" 1c
write seaenv\&.in input file
.IP "\(bu" 2
Main purpose for file
.IP "\(bu" 2
Typical inputs
.IP "\(bu" 2
Required inputs
.IP "\(bu" 2
Default values\&. 
.PP
.IP "\fBPage \fBStandard Motion Models\fP \fP" 1c
Write page for standard motion models\&. 
.IP "\fBPage \fBSubjective Motion Assessment\fP \fP" 1c
write documentation for Subjective Motion Assessment\&. There will probably also be some inputs to enter\&. 
.IP "\fBpage \fBSummary\fP \fP" 1c
write summary page for user guide\&.
.IP "\(bu" 2
WHat is the user guide for\&.
.IP "\(bu" 2
How is it different from the theory guide\&.
.IP "\(bu" 2
What sections should they read first\&. 
.PP
.IP "\fBPage \fBTutorials\fP \fP" 1c
Write tutorials\&.
.IP "\(bu" 2
__Very __ low priority\&. This will only happen after all other major features are implemented\&. 
.PP
.IP "\fBPage \fBUser Interface\fP \fP" 1c
write documentation for user interface\&.
.IP "\(bu" 2
What are the main things they should know about the interface\&. 
.PP
.IP "\fBPage \fBWave Directions\fP \fP" 1c
write documentation for wave directions\&.  
.IP "\fBPage \fBWave Frequencies\fP \fP" 1c
write documentation for wave frequencies\&.  
.IP "\fBPage \fBWave Spectra\fP \fP" 1c
write documentation for wave spectra\&. This is feedback to the user to show exactly what magnitude of wave spectra ofreq calculated for each specified wave direction\&.
.PP

