.TH "user_interface" 3 "Sun Apr 6 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
user_interface \- User Interface 
\fBTodo\fP
.RS 4
write documentation for user interface\&.
.IP "\(bu" 2
What are the main things they should know about the interface\&.
.PP
.RE
.PP
.PP
.SH "General Information"
.PP
.PP
\fBInput Syntax\fP
.PP
\fBText File Inputs\fP
.PP
.SH "File Structure"
.PP
.PP
\fBFile Structure\fP
.PP
.SH "Input Files"
.PP
.PP
\fBInput Files\fP 
