.TH "_c_p_p__comments" 3 "Sat Apr 5 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_c_p_p__comments \- CPP File Comment Standard 
.SH "Format of Coding for \&.CPP Files"
.PP
.PP
.SH "Commenting of Files"
.PP
.PP
.SH "Required Text for Every \&.CPP File"
.PP
.PP
Place the following text at the top of every cpp file\&. This is a legal protection to ensure we don't get a lawsuit\&. Otherwise, comment styles are completely free within the file\&. Please comment heavily to explain your code\&. 
