.TH "_header_comment" 3 "Sat Apr 5 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_header_comment \- Header Comment Standard 
/*----------------------------------------*- C++ -*------------------------------------------------------------------*\\ | O pen | OpenSea: The Open Source Seakeeping Suite | | S eakeeping | Web: www\&.opensea\&.dmsonline\&.us | | E valuation | | | A nalysis | | *------------------------------------------------------------------------------------------------------------------- 
