.TH "motion_model Directory Reference" 3 "Sat Apr 5 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
motion_model Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBeqnrotation\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeqnrotation\&.h\fP"
.br
.ti -1c
.RI "file \fBeqntranslation\&.cpp\fP"
.br
.ti -1c
.RI "file \fBeqntranslation\&.h\fP"
.br
.ti -1c
.RI "file \fBequationofmotion\&.cpp\fP"
.br
.ti -1c
.RI "file \fBequationofmotion\&.h\fP"
.br
.ti -1c
.RI "file \fBmodel6dof\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmodel6dof\&.h\fP"
.br
.ti -1c
.RI "file \fBmotionmodel\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmotionmodel\&.h\fP"
.br
.in -1c
