.TH "_u_m_l__process" 3 "Sat Apr 5 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_u_m_l__process \- UML Process Diagrams 
.SH "Header 1"
.PP
.PP
\fBOverall Process\fP Overall Process
.PP
\fBFile Reader Process\fP File Reader Process
.PP
\fBFile Writer Process\fP File Writer Process
.PP
\fBMotion Model Process\fP Motion Model Process
.PP
\fBMotion Solver Process\fP Motion Solver Process
.PP
\fBResonant Solver Process\fP Resonant Solver Process
.PP
\fBWave Calculations Process\fP Wave Calculations Process
.PP
\fBOutputs Calculation\fP Outputs Calculation 
