.TH "filereader.h" 3 "Sat Apr 5 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
filereader.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'parser\&.h'\fP
.br
\fC#include 'objectgroup\&.h'\fP
.br
\fC#include '\&.\&./global_objects/system\&.h'\fP
.br
\fC#include '\&.\&./global_objects/ofreqcore\&.h'\fP
.br
\fC#include 'dictionary\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBosea::FileReader\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBosea\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for oFreq from the source code\&.
