.TH "forcecross.h" 3 "Sat Apr 5 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
forcecross.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'forcereact\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBosea::ofreq::ForceCross\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBosea\fP"
.br
.ti -1c
.RI "namespace \fBosea::ofreq\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for oFreq from the source code\&.
