.TH "globalsolution.h" 3 "Sat Apr 5 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
globalsolution.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'outputderived\&.h'\fP
.br
\fC#include <QtGlobal>\fP
.br
\fC#include '\&.\&./global_objects/solutionset\&.h'\fP
.br
\fC#include '\&.\&./global_objects/solution\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBosea::ofreq::GlobalSolution\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBosea\fP"
.br
.ti -1c
.RI "namespace \fBosea::ofreq\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::complex< double > \fBosea::ofreq::complexDouble\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for oFreq from the source code\&.
