.TH "osea::ofreq::GlobalAcceleration" 3 "Sat Apr 5 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
osea::ofreq::GlobalAcceleration \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <globalacceleration\&.h>\fP
.PP
Inherits \fBosea::ofreq::GlobalSolution\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlobalAcceleration\fP ()"
.br
.ti -1c
.RI "\fBGlobalAcceleration\fP (\fBOutputsBody\fP *input)"
.br
.RI "\fIConstructor that also sets the pointer to the \fBOutputsBody\fP object which contains the \fBOutputDerived\fP object\&. \fP"
.ti -1c
.RI "\fB~GlobalAcceleration\fP ()"
.br
.ti -1c
.RI "void \fBsetDerivative\fP (int ord)"
.br
.RI "\fISets the order of the derivative for the object\&. \fP"
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
This class represents the Global Acceleraion \fBSolution\fP\&. 
.PP
Definition at line 86 of file globalacceleration\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GlobalAcceleration::GlobalAcceleration ()"
This default constructor creates a Global Acceleration object\&. 
.PP
Definition at line 42 of file globalacceleration\&.cpp\&.
.SS "GlobalAcceleration::GlobalAcceleration (\fBOutputsBody\fP *input)"

.PP
Constructor that also sets the pointer to the \fBOutputsBody\fP object which contains the \fBOutputDerived\fP object\&. \fBParameters:\fP
.RS 4
\fIinput\fP Pointer to the \fBOutputsBody\fP objec that contains this \fBOutputDerived\fP object\&. Pointer passed by value\&.
.RE
.PP
\fBSee Also:\fP
.RS 4
setOutputsBody() 
.RE
.PP

.PP
Definition at line 51 of file globalacceleration\&.cpp\&.
.SS "GlobalAcceleration::~GlobalAcceleration ()"
The default destructor, nothing happens here\&. 
.PP
Definition at line 60 of file globalacceleration\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void GlobalAcceleration::setDerivative (intord)\fC [virtual]\fP"

.PP
Sets the order of the derivative for the object\&. \fBParameters:\fP
.RS 4
\fIord\fP Integer input that specifies the order of the derivative\&. Value can be anything from 0 or larger\&. Variable is passed by value\&. 
.RE
.PP

.PP
Reimplemented from \fBosea::ofreq::GlobalSolution\fP\&.
.PP
Definition at line 65 of file globalacceleration\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for oFreq from the source code\&.
