.TH "outputsbody.h" 3 "Sat Apr 5 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
outputsbody.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <complex>\fP
.br
\fC#include <QtGlobal>\fP
.br
\fC#include 'globalsolution\&.h'\fP
.br
\fC#include 'globalacceleration\&.h'\fP
.br
\fC#include 'globalmotion\&.h'\fP
.br
\fC#include 'globalvelocity\&.h'\fP
.br
\fC#include '\&.\&./global_objects/solutionset\&.h'\fP
.br
\fC#include '\&.\&./global_objects/body\&.h'\fP
.br
\fC#include '\&.\&./global_objects/ofreqcore\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBosea::ofreq::OutputsBody\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBosea\fP"
.br
.ti -1c
.RI "namespace \fBosea::ofreq\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef std::vector
.br
< std::complex< double > > \fBosea::ofreq::cx_vector\fP"
.br
.RI "\fIType definition for a vector of complex numbers\&. Used to return the calculated output\&. \fP"
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for oFreq from the source code\&.
