.TH "seaenviroment.h" 3 "Sat Apr 5 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
seaenviroment.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'wavespectrummodel\&.h'\fP
.br
\fC#include 'wavespreadmodel\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSeaEnviroment\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for oFreq from the source code\&.
