.TH "todo" 3 "Sat Apr 5 2014" "Version 0.4" "oFreq" \" -*- nroff -*-
.ad l
.nh
.SH NAME
todo \- Todo List 
.IP "\fBPage \fBFile Reader Process\fP \fP" 1c
UML File Reader Diagram 
.IP "\fBPage \fBFile Writer Process\fP \fP" 1c
{file writer process diagram\&. May need to combine this with the Outputs Calculation UML process diagram\&.} 
.IP "\fBPage \fBMotion Model Process\fP \fP" 1c
UML Motion Model Process Diagram 
.IP "\fBPage \fBMotion Solver Process\fP \fP" 1c
UML Motion Solver Process 
.IP "\fBPage \fBOutputs Calculation\fP \fP" 1c
UML Outputs Calculation Process Diagram 
.IP "\fBPage \fBOverall Process\fP \fP" 1c
UML Overall process diagram 
.IP "\fBPage \fBResonant Solver Process\fP \fP" 1c
UML resonant solver process diagram 
.IP "\fBPage \fBWave Calculations Process\fP \fP" 1c
UML wave Calculations process diagram\&. 
.PP
create wave calculations code
.PP

